create table public.temp_migration (
    id bigint generated by default as identity primary key,

    source_schema VARCHAR(255) NOT NULL,
    source_table VARCHAR(255) NOT NULL,
    source_column VARCHAR(255) NOT NULL,
    old_id TEXT NOT NULL,
    new_id TEXT NOT NULL,

    CONSTRAINT temp_migration_unique UNIQUE (source_schema, source_table, source_column, old_id)
);


CREATE OR REPLACE FUNCTION get_table_hierarchy(source_schema text DEFAULT 'public')
RETURNS text[]
LANGUAGE plpgsql
AS $$
DECLARE
    sorted_tables    text[] := '{}';
    remaining_tables text[];
    independent      text[];
BEGIN
    -- collect all base tables in the schema
    SELECT array_agg(t.relname::text ORDER BY t.relname)
    INTO remaining_tables
    FROM pg_class t
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE n.nspname = source_schema AND t.relkind = 'r';

    IF remaining_tables IS NULL THEN
        RETURN sorted_tables;
    END IF;

    -- iteratively pick tables whose FKs only reference already-sorted (or self) tables
    WHILE array_length(remaining_tables, 1) > 0 LOOP
        SELECT array_agg(tbl ORDER BY tbl)
        INTO independent
        FROM unnest(remaining_tables) AS tbl
        WHERE NOT EXISTS (
            SELECT 1
            FROM pg_constraint c
            JOIN pg_class src ON src.oid = c.conrelid
            JOIN pg_namespace n ON n.oid = src.relnamespace
            JOIN pg_class ref ON ref.oid = c.confrelid
            JOIN pg_namespace rn ON rn.oid = ref.relnamespace
            WHERE c.contype = 'f'
              AND n.nspname = source_schema
              AND src.relname = tbl
              AND rn.nspname = source_schema
              AND ref.relname <> tbl
              AND ref.relname = ANY(remaining_tables)
        );

        IF independent IS NULL OR array_length(independent, 1) = 0 THEN
            -- cycle: append whatever is left and stop
            RAISE WARNING 'Cycle detected in FK graph for schema %; appending remaining tables: %', source_schema, remaining_tables;
            sorted_tables := sorted_tables || remaining_tables;
            EXIT;
        END IF;

        sorted_tables := sorted_tables || independent;
        remaining_tables := ARRAY(
            SELECT unnest(remaining_tables)
            EXCEPT
            SELECT unnest(independent)
        );
    END LOOP;

    RETURN sorted_tables;
END $$;


CREATE OR REPLACE FUNCTION migrate_table(source_schema text, target_schema text, tbl text)
RETURNS text
LANGUAGE plpgsql AS $$
DECLARE
    pk_col        text;
    pk_type       text;
    col_list      text[];
    select_exprs  text[] := ARRAY[]::text[];
    col           text;
    fk_cols       text[];
    fk_ref_tables text[];
    fk_ref_cols   text[];
    fk_col_types  text[];
    i             int;
    insert_sql    text;
    rows_inserted bigint;
    col_type      text;
BEGIN
    -- determine what is PK in the table
    SELECT a.attname, tpe.typname INTO pk_col, pk_type
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = c.conkey[1]
    JOIN pg_type tpe ON tpe.oid = a.atttypid
    WHERE c.contype = 'p' AND n.nspname = source_schema AND t.relname = tbl AND array_length(c.conkey, 1) = 1;

    IF pk_col IS NULL THEN
        RAISE NOTICE 'Skipping %.%', source_schema, tbl;
        RETURN 0;
    END IF;

    -- generate list of columns
    SELECT array_agg(column_name::text ORDER BY ordinal_position)
    INTO col_list
    FROM information_schema.columns
    WHERE table_schema = source_schema AND table_name = tbl AND column_name <> pk_col;

    IF col_list IS NULL THEN
        col_list := '{}';
    END IF;

    -- generate list of FKs to other tables + type of each FK column
    SELECT
        array_agg(a.attname::text   ORDER BY a.attname),
        array_agg(rt.relname::text  ORDER BY a.attname),
        array_agg(ra.attname::text  ORDER BY a.attname),
        array_agg(tpe.typname::text ORDER BY a.attname)
    INTO fk_cols, fk_ref_tables, fk_ref_cols, fk_col_types
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY(c.conkey)
    JOIN pg_class rt ON rt.oid = c.confrelid
    JOIN pg_attribute ra ON ra.attrelid = rt.oid AND ra.attnum = ANY(c.confkey)
    JOIN pg_type tpe ON tpe.oid = a.atttypid
    WHERE c.contype = 'f' AND n.nspname = source_schema AND t.relname = tbl;

    -- generate SELECT expressions
    FOREACH col IN ARRAY col_list LOOP
        i := array_position(fk_cols, col);
        IF i IS NOT NULL THEN
            col_type := fk_col_types[i];

            -- Cast based on actual column type: uuid vs numeric
            IF col_type = 'uuid' THEN
                select_exprs := select_exprs || format(
                    '(SELECT new_id::uuid FROM public.temp_migration WHERE source_schema=%L AND source_table=%L AND source_column=%L AND old_id::uuid=src.%I::uuid)',
                    source_schema, fk_ref_tables[i], fk_ref_cols[i], col
                );
            ELSE
                select_exprs := select_exprs || format(
                    '(SELECT new_id::numeric FROM public.temp_migration WHERE source_schema=%L AND source_table=%L AND source_column=%L AND old_id::numeric=src.%I::numeric)',
                    source_schema, fk_ref_tables[i], fk_ref_cols[i], col
                );
            END IF;
        ELSE
            select_exprs := select_exprs || format('src.%I', col);
        END IF;
    END LOOP;

    -- create sql for copying data (the rest is the same)
    IF pk_col = 'uuid' THEN
        insert_sql := format(
            'WITH src AS (SELECT %I, %s FROM %I.%I),
             ins AS (INSERT INTO %I.%I (%I, %s) SELECT src.%I, %s FROM src RETURNING %I)
             INSERT INTO public.temp_migration(source_schema, source_table, source_column, old_id, new_id)
             SELECT %L, %L, %L, src.%I, src.%I FROM src',
            pk_col, (SELECT string_agg(format('%I', c), ', ') FROM unnest(col_list) c), source_schema, tbl,
            target_schema, tbl, pk_col, (SELECT string_agg(format('%I', c), ', ') FROM unnest(col_list) c), pk_col, array_to_string(select_exprs, ', '), pk_col,
            source_schema, tbl, pk_col, pk_col, pk_col
        );
    ELSE
        insert_sql := format(
            'WITH src AS (SELECT %I, %s FROM %I.%I),
             ins AS (INSERT INTO %I.%I (%s) SELECT %s FROM src RETURNING %I),
             src_row AS (select %I, row_number() over () as row from src),
             ins_row as (select %I, row_number() over () as row from ins)
             INSERT INTO public.temp_migration(source_schema, source_table, source_column, old_id, new_id)
             SELECT %L, %L, %L, src_row.%I, ins_row.%I FROM src_row JOIN ins_row ON src_row.row = ins_row.row',
            pk_col, (SELECT string_agg(format('%I', c), ', ') FROM unnest(col_list) c), source_schema, tbl,
            target_schema, tbl, (SELECT string_agg(format('%I', c), ', ') FROM unnest(col_list) c), array_to_string(select_exprs, ', '), pk_col,
            pk_col,
            pk_col,
            source_schema, tbl, pk_col, pk_col, pk_col
        );
    END IF;

    BEGIN
        EXECUTE insert_sql;
    EXCEPTION
        WHEN OTHERS THEN
            RAISE WARNING 'Migration failed for table %.%', source_schema, tbl;
            RAISE WARNING 'SQL: %', insert_sql;
            RAISE EXCEPTION '%', SQLERRM;
    END;

    GET DIAGNOSTICS rows_inserted = ROW_COUNT;

    RAISE NOTICE 'Imported %.%: % records', source_schema, tbl, rows_inserted;
    RETURN rows_inserted;
END $$;


CREATE OR REPLACE FUNCTION migrate_schema(tables text[], source_schema text DEFAULT 'public', migration_schema text DEFAULT 'public')
RETURNS text[]
LANGUAGE plpgsql
AS $$
DECLARE
    migrated_tables text[] := '{}';
    tbl text;
BEGIN
    IF source_schema = migration_schema THEN
        RAISE EXCEPTION 'source_schema and migration_schema cannot be equal (%).', source_schema;
    END IF;

    FOREACH tbl IN ARRAY tables
    LOOP
        PERFORM migrate_table(source_schema, migration_schema, tbl);
        migrated_tables := array_append(migrated_tables, tbl);
    END LOOP;

    RETURN migrated_tables;
END $$;